### ISSUE TITLE
Configure Database

### ISSUE THREAD

**Issue by aasmal97** [chingu-voyages/v47-tier3-team-35#14]
### Overview
- Configure MongoDB and Prisma
### To-do
- [x] Configure MongoDB Cloud/Atlas
   - [x] Invite every user with their email as an admin to the MongoDB Cloud Instance
- [x] Configure Prisma with MongoDB URI
   - [x] This secret should be stored in HashiCorp #37
