### ISSUE TITLE
Configure AWS Resources

### ISSUE THREAD

**Issue by aasmal97** [chingu-voyages/v47-tier3-team-35#16]
### Overview
- Create AWS account + Project, and Invite all team members to have access. You can use IAM, and assign us roles as administrators.
- Create Cloudfront and S3 Bucket, and link them together.
### To-do
- [x] Create AWS account
- [x] Create Project
- [x] Invite team members as Admins using IAM
- [x] Create a service account in IAM 
   - [x] The user should be created with a secret key, as the mode of authentication. Store this secret key in Hashicorp Secrets #37  
   - [x] Attach ONLY Full S3 Admin and Full Cloudfront Admin policies to it. We don't really need to mess with anything else.
- [x] Create an S3 Bucket with default settings. Do not attach a policy on it. We want this private. 
- [x] Create a Cloudfront Distribution 
   - [x] Ensure you select the previously created S3 bucket to it.  
   - [x] Copy Distribution URL and add it to Hashicorp Secrets #37 

Note:
- This may require adding some form of payment information for billing, but do not worry, you will never be charged at all for using this service. AWS free tier limits are very, VERY generous.
