### ISSUE TITLE
Create Frontend on Room/Item Catalog Page

### ISSUE THREAD

**Issue by aasmal97** [chingu-voyages/v47-tier3-team-35#26]

**Comment by aasmal97** [comment]
### Overview
- Code the frontend for the design outlined here #24    
### To-do-list
- [ ] Create mock data using Prisma models as a reference. You can use Prisma's exported type for the model, to ensure type safety. 
- [ ] Create Item Picture Banner 
- [ ] Create Product Info Section
- [ ] Create Product Info Form (available upon clicking edit)
- [ ] Create Item History + Tracker Side Panel
- [ ] Create Recently Updated/Viewed Product Section

Note: Once each item is complete, check the items that complete by editing this markdown, and replacing `[ ]` with `[x]`
